jobs:
- job: Linux
  pool:
    vmImage: 'ubuntu-16.04'
  steps:
  - bash: |
      wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O ~/miniconda.sh
      bash ~/miniconda.sh -b -p $HOME/miniconda
      export PATH="$HOME/miniconda/bin:$PATH"
      conda env create -f environment-linux.yml
      source activate crash-model
      conda install -y pylint
      cd src
      pylint pipeline.py initialize_city.py data/*.py visualization/*.py data_standardization/*.py models/*.py features/*.py tools/*.py
      python3 -m pip install -U pytest
      py.test --cov=./
    displayName: 'Run tests on Linux'

- job: macOS
  pool:
    vmImage: 'macOS-10.13'
  steps:
  - bash: |
      wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O ~/miniconda.sh
      bash ~/miniconda.sh -b -p $HOME/miniconda
      export PATH="$HOME/miniconda/bin:$PATH"
      conda env create -f environment.yml
      source activate crash-model
      conda install -y pylint
      cd src
      pylint pipeline.py initialize_city.py data/*.py visualization/*.py data_standardization/*.py models/*.py features/*.py tools/*.py
      python3 -m pip install -U pytest
      py.test --cov=./
    displayName: 'Run tests on Mac'




- job: Windows
  pool:
    vmImage: 'vs2017-win2016'
  steps:
  - script: echo hello from Windows
