jobs:
- job: Linux
  pool:
    vmImage: 'ubuntu-16.04'
  steps:
  - bash: |
      wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O ~/miniconda.sh
      bash ~/miniconda.sh -b -p $HOME/miniconda
      export PATH="$HOME/miniconda/bin:$PATH"
      conda env create -f environment_linux.yml
      source activate crash-model
      cd src
      pylint pipeline.py initialize_city.py data/*.py visualization/*.py data_standardization/*.py models/*.py features/*.py tools/*.py
      py.test --cov=./
      bash <(curl https://codecov.io/bash) -t $env:TOKEN
    env:
        TOKEN: $(codecov.token)
    displayName: 'Run tests on Linux'

- job: macOS
  pool:
    vmImage: 'macOS-10.13'
  steps:
  - bash: |
      . /usr/local/miniconda/etc/profile.d/conda.sh
      sudo chown -R $USER $CONDA
      conda env create --quiet --file environment_mac.yml
      conda activate crash-model
      conda install -y pylint
      cd src
      pylint pipeline.py initialize_city.py data/*.py visualization/*.py data_standardization/*.py models/*.py features/*.py tools/*.py
      python3 -m pip install -U pytest
      py.test
  displayName: 'Run tests on Mac'


- job: Windows
  pool:
    vmImage: 'vs2017-win2016'
  steps:
  - powershell: |
      Write-Host "##vso[task.prependpath]$env:CONDA\Scripts"
  - script: |
      conda env create --file environment.yml
      call activate crash-model
      conda env export

