# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: 'Ubuntu-16.04'

steps:

- task: UsePythonVersion@0
  inputs:
    versionSpec: '3.6'
    architecture: 'x64'

- script: |
    python -m pip install --upgrade pip && pip3 install --upgrade setuptools
  displayName: 'Upgrade pip and setuptools'
  continueOnError: false

- bash: |
    wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O ~/miniconda.sh
    bash ~/miniconda.sh -b -p $HOME/miniconda
    export PATH="$HOME/miniconda/bin:$PATH"
    conda env create -f environment.yml
    source activate crash-model
  displayName: Create conda environment

- script: |
    pip install --upgrade pip
    python3 -m pip install pylint
    python3 -m pip install -U pytest
  displayName: 'Install pylint etc'

- bash: |
    cd src
    pylint pipeline.py initialize_city.py data/*.py visualization/*.py data_standardization/*.py models/*.py features/*.py tools/*.py
    py.test --cov=./
  displayName: 'run tests'