name: crash-model
channels:
- conda-forge
- defaults
dependencies:
- widgetsnbextension=3.2.1=py36_0
- codecov
- fiona
- flask
- folium
- geopandas=0.5.1
- geocoder
- geojson=2.4.1
- ipdb
- ipython
- jupyter
- matplotlib
- numpy
- openpyxl
- osmnx
- pandas
- py-xgboost
- pylint
- pyproj
- pytest
- python=3.6
- pyyaml
- pytest-cov
- rtree
- ruamel.yaml
- seaborn
- scikit-learn
- shapely=1.6.4
- tzlocal
#- xgboost
- xlrd
- zstd

