name: boston-crash-model
channels:
- conda-forge
- defaults
dependencies:
- backports.shutil_get_terminal_size=1.0.0=py27_1
- branca=0.2.0=py27_0
- ca-certificates=2017.4.17=0
- certifi=2017.4.17=py27_0
- descartes=1.1.0=py27_0
- entrypoints=0.2.3=py27_1
- enum34=1.1.6=py27_1
- expat=2.2.1=vc9_0
- fiona=1.7.5=np112py27_0
- folium=0.3.0=py27_0
- freetype=2.7=vc9_1
- freexl=1.0.2=vc9_1
- functools32=3.2.3.2=py27_1
- gdal=2.1.3=np112py27_vc9_3
- geopandas=0.2.1=py27_4
- geos=3.5.1=vc9_1
- hdf4=4.2.12=vc9_0
- hdf5=1.8.17=vc9_11
- html5lib=0.9999999=py27_0
- icu=58.1=vc9_1
- ipython=5.4.1=py27_0
- kealib=1.4.7=vc9_0
- krb5=1.14.2=vc9_0
- libiconv=1.14=vc9_4
- libnetcdf=4.4.1.1=vc9_4
- libpng=1.6.28=vc9_0
- libpq=9.5.4=vc9_4
- libspatialindex=1.8.5=vc9_1
- libspatialite=4.3.0a=vc9_15
- libtiff=4.0.6=vc9_7
- libxml2=2.9.4=vc9_4
- matplotlib=2.0.0=np112py27_3
- nbconvert=5.2.1=py27_1
- openjpeg=2.1.2=vc9_3
- pandoc=1.19.2=0
- pcre=8.39=vc9_0
- proj4=4.9.3=vc9_4
- pyqt=5.6.0=py27_4
- pyzmq=16.0.2=py27_2
- qt=5.6.2=vc9_1
- rtree=0.8.3=py27_0
- scandir=1.5=py27_1
- setuptools=33.1.1=py27_0
- shapely=1.5.17=np112py27_3
- sip=4.18=py27_1
- six=1.10.0=py27_1
- ssl_match_hostname=3.5.0.1=py27_1
- webencodings=0.5=py27_0
- wincertstore=0.2=py27_0
- xerces-c=3.1.4=vc9_3
- alabaster=0.7.10=py27_0
- astroid=1.4.9=py27_0
- babel=2.4.0=py27_0
- backports=1.0=py27_0
- backports_abc=0.5=py27_0
- bleach=1.5.0=py27_0
- chardet=3.0.4=py27_0
- click=6.7=py27_0
- click-plugins=1.0.3=py27_0
- cligj=0.4.0=py27_0
- colorama=0.3.9=py27_0
- configparser=3.5.0=py27_0
- curl=7.52.1=vc9_0
- cycler=0.10.0=py27_0
- decorator=4.0.11=py27_0
- docutils=0.13.1=py27_0
- et_xmlfile=1.0.1=py27_0
- imagesize=0.7.1=py27_0
- ipykernel=4.6.1=py27_0
- ipython_genutils=0.2.0=py27_0
- ipywidgets=6.0.0=py27_0
- isort=4.2.15=py27_0
- jdcal=1.3=py27_0
- jedi=0.10.2=py27_2
- jinja2=2.9.5=py27_0
- jpeg=9b=vc9_0
- jsonschema=2.5.1=py27_0
- jupyter=1.0.0=py27_0
- jupyter_client=5.1.0=py27_0
- jupyter_console=5.1.0=py27_0
- jupyter_core=4.3.0=py27_0
- lazy-object-proxy=1.3.1=py27_0
- markupsafe=1.0=py27_0
- mistune=0.7.4=py27_0
- mkl=2017.0.3=0
- munch=2.1.1=py27_0
- nbformat=4.3.0=py27_0
- notebook=5.0.0=py27_0
- numpy=1.12.1=py27_0
- numpydoc=0.6.0=py27_0
- openpyxl=2.4.8=py27_0
- openssl=1.0.2l=vc9_0
- pandas=0.19.2=np112py27_1
- pandocfilters=1.4.1=py27_0
- path.py=10.3.1=py27_0
- pathlib2=2.3.0=py27_0
- patsy=0.4.1=py27_0
- pickleshare=0.7.3=py27_0
- pip=9.0.1=py27_0
- prompt_toolkit=1.0.14=py27_0
- psutil=5.2.2=py27_0
- psycopg2=2.7.1=py27_0
- pycodestyle=2.3.1=py27_0
- pyflakes=1.5.0=py27_0
- pygments=2.2.0=py27_0
- pylint=1.6.4=py27_1
- pyparsing=2.2.0=py27_0
- pyproj=1.9.5.1=py27_0
- pysal=1.13.0=py27_0
- python=2.7.13=1
- python-dateutil=2.6.0=py27_0
- pytz=2017.2=py27_0
- qtawesome=0.4.4=py27_0
- qtconsole=4.3.0=py27_0
- qtpy=1.2.1=py27_0
- requests=2.14.2=py27_0
- rope=0.9.4=py27_1
- scikit-learn=0.18.1=np112py27_1
- scipy=0.19.1=np112py27_0
- seaborn=0.7.1=py27_0
- simplegeneric=0.8.1=py27_0
- singledispatch=3.4.0.3=py27_0
- snowballstemmer=1.2.1=py27_0
- sphinx=1.6.2=py27_0
- sphinxcontrib=1.0=py27_0
- sphinxcontrib-websupport=1.0.1=py27_0
- sqlalchemy=1.1.11=py27_0
- sqlite=3.13.0=vc9_1
- statsmodels=0.8.0=np112py27_0
- testpath=0.3=py27_0
- tornado=4.5.1=py27_0
- traitlets=4.3.2=py27_0
- typing=3.6.1=py27_0
- vc=9=0
- vincent=0.4.4=py27_0
- vs2008_runtime=9.00.30729.5054=0
- wcwidth=0.1.7=py27_0
- wheel=0.29.0=py27_0
- widgetsnbextension=2.0.0=py27_0
- win_unicode_console=0.5=py27_0
- wrapt=1.10.10=py27_0
- zlib=1.2.11=vc9_0
- pip:
  - backports-abc==0.5
  - backports.shutil-get-terminal-size==1.0.0
  - backports.ssl-match-hostname==3.5.0.1
  - et-xmlfile==1.0.1
  - geocoder==1.30.1
  - ipython-genutils==0.2.0
  - jupyter-client==5.1.0
  - jupyter-console==5.1.0
  - jupyter-core==4.3.0
  - prompt-toolkit==1.0.14
  - ratelim==0.1.6
  - win-unicode-console==0.5

