name: crash-model
channels:
- conda-forge
- defaults
dependencies:
- codecov
- fiona
- flask
- folium
- geopandas=0.5.1=py_0 # pinned
- geocoder
- geojson=2.4.1 # pinned
- ipdb
- ipython
- jupyter
- matplotlib
- numpy
- openpyxl
- osmnx=0.11
- pandas=1.0.5 # pinned
- py-xgboost
- pylint
- pyproj=2.2.1 # pinned
- pytest
- python=3.6
- pyyaml
- pytest-cov
- rtree
- ruamel.yaml
- seaborn
- scikit-learn
- shapely
- tzlocal
#- xgboost
- xlrd
- zstd

