name: boston-crash-model
channels:
- conda-forge
- defaults
dependencies:
- fiona
- folium
- geopandas
- geocoder
- geojson
- ipdb
- ipython
- jupyter
- matplotlib
- numpy
- openpyxl
- osmnx
# Weird conda packaging bug, will want to revisit version of pandas later
- pandas=0.22
- pyproj
- pytest
- python=3.6
- pyyaml
- rtree
- scikit-learn
- shapely
- xlrd