---
name: CI

on:
  push:
    branches: ["master"]
  pull_request:
    branches: ["master"]

jobs:
  tests:
    name: "Tests"
    runs-on: "ubuntu-latest"
    
    steps:
      - uses: "actions/checkout@v2"
      - name: "Install dependencies"
        run: |
          set -xe
          set -eo pipefail
          wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.s\
h -O ~/miniconda.sh
          bash ~/miniconda.sh -b -p $HOME/miniconda
          export PATH="$HOME/miniconda/bin:$PATH"
          conda env create -f environment_linux.yml
          source activate crash-model
          cd src
          pylint pipeline.py initialize_city.py data/*.py visualization/*.py data_s\
tandardization/*.py models/*.py features/*.py tools/*.py  
          py.test --cov=./