# City name
city: Washington, DC, USA
# The folder under data where this city's data is stored
name: dc
city_latitude: 38.9071923
city_longitude: -77.0368707
# If given, limit crashes to after start_year and before end_year
start_year: 2014
end_year: 2017

##############################################################################
# Configuration for data transformation

# crash file configurations
crashes_files:
  Crashes_in_DC.csv:
    required:
      id: OBJECTID
      latitude: Y
      longitude: X
      date: REPORTDATE
    optional:
      summary: MAR_ADDRESS
      vehicles: TOTAL_VEHICLES
      bikes: TOTAL_BICYCLES

# List of concern type information
concern_files:
  - name: concern
    filename: Vision_Zero_Safety.csv
    latitude: Y
    longitude: X
    time: REQUESTDATE

# concern column name
# leave as '' if not adding concerns
concern: visionzero

# week on which to predict crashes (week, year)
# will output predictions for all weeks up to this week
# Choose a week towards the end of your crash data set
# in format [month, year]
time_target: [51, 2016]

