# City name
city: Philadelphia, Pennslyvania, USA
# The folder under data where this city's data is stored
name: philly
# City centerpoint latitude & longitude
city_latitude: 39.9526
city_longitude: -75.1652
# Radius of city's road network from centerpoint in km (required if OSM has no polygon data)
city_radius: 15
# If given, limit crashes to after start_year and before end_year
start_year: 2011
end_year: 2015
level: 'segment'
##############################################################################
# Configuration for data standardization
# crash file configurations
crashes_files:
    vztest.csv:
        required:
            id: OBJECTID
            latitude: LATITUDE
            longitude: LONGITUDE
            date_complete: 
            date_year: CRASH_YEAR
            date_month: CRASH_MONTH
            date_day:
            time: 
            time_format: 
        optional:
            intersection: INTERSECT_TYPE

##############################################################################

# Additional city-specific features can be added from maps by setting
# these variables below
data_source: 
  - name: DVRPCTrafficVolume 
    filename: DVRPC_Traffic_Counts.csv
    latitude: LATITUDE 
    longitude: LONGITUDE
    date: SETDATE
    notes: 
    # Feature is categorical (f_cat) or continuous (f_cont)\n" +
    feat: f_cont
    # feat_agg (feature aggregation) can be total count 'default' or 'latest value' \n" +
    feat_agg: latest
    # if latest, the desired value 
    value: RECORDNUM 
