# City name
city: Boston, Massachusetts, USA
# The folder under data where this city's data is stored
name: boston
city_latitude: 42.3600825
city_longitude: -71.0588801
# If given, limit crashes to after start_year and before end_year
start_year: 2015
end_year: 2018

##############################################################################
# Configuration for data standardization

# List of concern type information
concern_files:
  - name: concern
    filename: Vision_Zero_Entry.csv
    latitude:
    longitude:
    time:
  - name: see_click_fix
    filename: bos_scf.csv
    latitude:
    longitude:
    time: created

# crash file configurations
crashes_files:
    vzopendata.csv:
        required:
            id: ID
            latitude: lat
            longitude: long
            date: dispatch_ts
        optional:
            summary: location_type
            vehicles: mode_type
            bikes: mode_type

##############################################################################

# Additional city-specific features can be added from maps by setting
# these variables below

# If you are adding another map and its features to the open street map,
# give it here.  Required to be in 3857 projection
extra_map: ../data/boston/raw/maps/ma_cob_spatially_joined_streets.shp

# Additional features to add from the additional map.
# This is required if extra_map is given
additional_features: AADT SPEEDLIMIT Struct_Cnd Surface_Tp F_F_Class

##############################################################################

# configuration for running the model training and prediction

# concern column name
# leave as '' if not adding concerns
concern: 'visionzero'

# atr filepath (should be in processed subfolder)
# leave as '' if not adding atrs
atr: 'atrs_predicted.csv'
# atr column names as list
atr_cols:
- speed_coalesced
- volume_coalesced

# tmc filepath (should be in processed subfolder)
# leave as '' if not adding tmcs
tmc: 'tmc_summary.json'
# tmc column names as list
tmc_cols:
- Conflict

# week on which to predict crashes (week, year)
# as is, will end up outputting predictions for all weeks up to this week
# TODO: Make this more relevant for control
time_target: [15, 2017]

# continuous features
f_cont:
- AADT

# categorical features
f_cat:
- 'SPEEDLIMIT'
- 'Struct_Cnd'
- 'Surface_Tp'
- 'F_F_Class'

# make categorical into dummies, standardize continuous
# usually necessary/important if want to use linear models
process: True
