# City name
city: Boston, Massachusetts, USA
# The folder under data where this city's data is stored
name: boston
# If given, limit crashes to after start_year and before end_year
start_year: 
end_year:

# List of concern type information
concern_files:
  - name: concern
    filename: Vision_Zero_Entry.csv
    latitude:
    longitude:
    time:
  - name: see_click_fix
    filename: bos_scf.csv
    latitude:
    longitude:
    time: created

# crash file configurations
crashes_files:
  2015motorvehicles_with_modetype.csv:
    required:
      id: CAD_EVENT_REL_COMMON_ID
      latitude: Y
      longitude: X
      date: CALENDAR_DATE
      time: TIME,
    optional:
      summary: FIRST_EVENT_SUBTYPE
      vehicles: mode_type
      bikes: mode_type
  cad_crash_events_with_transport_2016_wgs84_with_modetype.csv:
    required:
      id: CAD_EVENT_REL_COMMON_ID
      latitude: Y
      longitude: X
      date: CALENDAR_DATE
      time: TIME
    optional:
      summary: FIRST_EVENT_SUBTYPE
      vehicles: mode_type
      bikes: mode_type
  2017motorvehicles_with_modetype.csv:
    required:
      id: CAD_EVENT_REL_COMMON_ID
      latitude: Y
      longitude: X
      date: CALENDAR_DATE
      time: TIME,
    optional:
      summary: FIRST_EVENT_SUBTYPE
      vehicles: mode_type
      bikes: mode_type
