# City name
city: Cambridge, Massachusetts, USA
# The folder under data where this city's data is stored
name: cambridge
# If given, limit crashes to after start_year and before end_year
start_year: 
end_year:


# List of concern type information
concern_files:
  - name: concern
    filename: Commonwealth_Connect_Service_Requests.csv
    latitude: lat
    longitude: lng
    time: ticket_created_date_time

# crash file configurations
crashes_files:
  crash_data_through_2017.csv:
    required:
      id: ID
      latitude: Y
      longitude: X
      date: Date Time
    optional:
      summary: V1 First Event
      vehicles:
      bikes:
      address: Location